In [1]:
# includem instrumentele necesare (bibliotecile)
import numpy as np 
import random

In [2]:
# definim functia de activare (functia logistica)
def sigmoidala(x):
    return 1 / (1 + np.exp(-x))

In [3]:
# definim o functie care returneaza derivata sigmoidalei
def sigm_derivata(x):
    return x * (1 - x)# sigmoidala(x) * (1-sigmoidala(x))
# definim functia OR dintre 0 si 1
def f_or(x1, x2, x3):
    if (x1 == 0 and x2 == 0 and x3 == 0):
        return 0
    else: 
        return 1

In [4]:
# initializam o matrice cu 10 exemple de caracteristici aleatorii pentru inrare
date_intrare =  np.random.randint(2, size=(10, 3))
print(date_intrare)

[[1 1 0]
 [0 1 1]
 [0 0 0]
 [0 0 1]
 [0 1 1]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 1 1]
 [0 0 0]]


In [5]:
# calculam functia OR pentru fiecare exemplu din exemplele de intrare
date_iesire = [f_or(x1,x2,x3) for x1, x2, x3 in date_intrare]

In [6]:
# initializam ponderile cu un numar real random intre 0 si 1
pondere1 = random.random()
pondere2 = random.random()
pondere3 = random.random()
print(pondere1, pondere2, pondere3)
print(date_iesire)

0.9694018772933451 0.637843733133151 0.019245497247109555
[1, 1, 0, 1, 1, 1, 1, 1, 1, 0]


In [7]:
# initializam constanta de invatare cu 0.05 (in dependenta de rezultat o putem modifica)
c = 0.01

In [8]:
# intr-o 100 de iteratii
for j in range(10000):
    
    # luam fiecare exemplu pe rand (din datele de invatare)
    for i, (x1, x2, x3) in enumerate(date_intrare):
        
        
        # calculam activarea totala (sigmoid pe suma ponderata)
        iesire = sigmoidala((x1 * pondere1) + (x2 * pondere2) + (x3 * pondere3))
        
        # calculam eroarea
        eroare = ((date_iesire[i] - iesire)**2)/2

        # caclulam derivata integrala cu constata de invatare
        ajustare = eroare * sigm_derivata(iesire) * c
        
        pondere1 = pondere1 + ajustare
        pondere2 = pondere2 + ajustare
        pondere3 = pondere3 + ajustare
        #print("{} or {} | {} {} {}".format(x1, x2, iesire, date_iesire[i], eroare))
        #print(pondere1, pondere2)

In [9]:
for i, (x1, x2, x3) in enumerate(date_intrare):
    iesire = sigmoidala((x1 * pondere1) + (x2 * pondere2) + (x3 * pondere3))
    print("{} or {} or {} | Corect: {} Neuron: {}".format(x1, x2, x3, date_iesire[i], iesire))


1 or 1 or 0 | Corect: 1 Neuron: 0.9999996538883716
0 or 1 or 1 | Corect: 1 Neuron: 0.9999991049163486
0 or 0 or 0 | Corect: 0 Neuron: 0.5
0 or 0 or 1 | Corect: 1 Neuron: 0.9987126416502243
0 or 1 or 1 | Corect: 1 Neuron: 0.9999991049163486
1 or 0 or 0 | Corect: 1 Neuron: 0.9995018102140895
1 or 0 or 0 | Corect: 1 Neuron: 0.9995018102140895
1 or 0 or 0 | Corect: 1 Neuron: 0.9995018102140895
1 or 1 or 1 | Corect: 1 Neuron: 0.9999999995538558
0 or 0 or 0 | Corect: 0 Neuron: 0.5


Concluzie:
La aceasta lucrare de laborator am implementat o simpla retea neurala,
am invatato si iam dat niste valori noi si am observat ca nea prezis rezultatul corect.